version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=mysql;Database=InvestmentDB;User=myuser;Password=myuserPassword;
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: InvestmentDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserPassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
