services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=mysql;Database=InvestmentDB;User=myuser;Password=myuserPassword;
    depends_on:
      - mysql
    command: sh -c "sleep 60 && dotnet InvestmentTracker.dll" 

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: InvestmentDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserPassword
